# Default configuration for train_classification.py
base_data_root: 'D:/glaucoma/data'
data_type: 'raw'
min_samples_per_group_for_stratify: 2
smdg_metadata_file: 'D:/glaucoma/data/raw/SMDG-19/metadata - standardized.csv'
smdg_image_dir: 'D:/glaucoma/data/raw/SMDG-19/full-fundus/full-fundus'
use_chaksu: true
chaksu_base_dir: 'D:/glaucoma/data/raw/Chaksu/Train/Train/1.0_Original_Fundus_Images'
chaksu_decision_dir: 'D:/glaucoma/data/raw/Chaksu/Train/Train/6.0_Glaucoma_Decision'
chaksu_metadata_dir: 'D:/glaucoma/data/raw/Chaksu/Train/Train/6.0_Glaucoma_Decision/Majority'
use_airogs: true
airogs_label_file: 'D:/glaucoma/data/raw/AIROGS/train_labels.csv'
airogs_image_dir: 'D:/glaucoma/data/raw/AIROGS/img'
airogs_num_rg_samples: 1000
airogs_num_nrg_samples: 9000
use_airogs_cache: false
model_name: 'vit_base_patch16_224'
num_classes: 2
image_size: 224
dropout_prob: 0.1
custom_weights_path: null
checkpoint_key: 'teacher'
use_timm_pretrained_if_no_custom: false
is_regression_to_classification: false
freeze_backbone_epochs: 0
backbone_lr_multiplier: 1.0
num_epochs: 25
batch_size: 8
eval_batch_size: 64
learning_rate: 0.0001
weight_decay: 0.05
early_stopping_patience: 0
grad_accum_steps: 4
seed: 42
num_workers: 0
use_amp: true
use_label_smoothing: false
label_smoothing_factor: 0.1
use_temperature_scaling: false
calibration_split_ratio: 0.3
temperature_lr: 0.01
temperature_max_iter: 50
use_mixup: false
mixup_alpha: 0.8
cutmix_alpha: 1.0
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_mode: 'batch'
save_mixup_samples: true
num_mixup_samples_to_save: 5
drop_last_batch: true
use_data_augmentation: true
base_output_dir: 'experiments/training_runs_glaucoma'
experiment_tag: ''
resume_from_checkpoint: null
num_epochs_to_add: 25
save_data_samples: false
num_data_samples_per_source: 3
run_gradcam_visualizations: false
num_gradcam_samples: 3
ft_strategy: 'full'
llrd_decay: 0.9
gradual_patience: 3
linear_probe_epochs: 10
