name: Basic CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Format check
      run: |
        black --check --diff src/ scripts/
        isort --check-only --diff src/ scripts/
    
    - name: Lint
      run: flake8 src/ scripts/
    
    - name: Test
      run: pytest
